# Generated by Django 4.2 on 2025-04-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiapp", "0002_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("tg_id", models.BigIntegerField(unique=True)),
                ("activated_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
