# Generated by Django 4.2 on 2025-04-22 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxiapp", "0003_activeuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="bot_token",
        ),
    ]
