# Generated by Django 4.2 on 2025-04-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taxiapp", "0004_remove_driver_bot_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="tg_id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
